/**
 * H2MS API
 * API for interacting with the H2MS backend.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Link {
    href: string;
}

export interface Links {
    self?: Link;
    location?: Link;
    children?: Link;
    parent?: Link;
}

export interface Location {
    address?: string;
    children?: Array<Location>;
    country?: string;
    id?: number;
    name?: string;
    parent?: Location;
    type?: string;
    zip?: string;
    _links?: Links;
}
